services:
  - type: web
    name: bloomskin-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://bloomskin.vercel.app
      - key: GOOGLE_CALLBACK_URL
        value: https://bloom-skin-backend.onrender.com/api/auth/google/callback
